from __future__ import annotations

from typing import List

from .vm import VmFunction


def _jni_signature(proto: str) -> str:
    """Convert a DEX prototype like (ILjava/lang/String;)V to a JNI signature."""
    return proto


def _native_symbol(class_name: str, name: str, proto: str) -> str:
    cls = class_name
    if cls.startswith("L") and cls.endswith(";"):
        cls = cls[1:-1]
    cls = cls.replace("/", "_")
    safe = name.replace("<", "_").replace(">", "_")
    flat = proto.replace("/", "_").replace(";", "_").replace("(", "_").replace(")", "_")
    flat = flat.replace("[", "_").replace("$", "_")
    return f"Java_{cls}_{safe}__{flat}"


def generate_jni(functions: List[VmFunction], package_stub: str = "com/nxshield/runtime") -> str:
    lines: List[str] = []
    lines.append("/* Auto-generated by NXShield. Self-developed JNI bridge. */")
    lines.append("#include <jni.h>")
    lines.append("#include \"nxvm.h\"")
    lines.append("")
    lines.append("extern \"C\" {")
    lines.append("")
    for fn in functions:
        sig = _jni_signature(fn.proto)
        symbol = _native_symbol(fn.class_name, fn.name, fn.proto)
        lines.append(f"/* {fn.key} */")
        lines.append(
            f"JNIEXPORT jvalue JNICALL {symbol}(JNIEnv* env, jobject thiz, ...)"
        )
        lines.append("{")
        lines.append(f"    return NXVM_Call({fn.method_idx}, env, thiz, __builtin_va_arg_pack());")
        lines.append("}")
        lines.append("")
    lines.append("}  /* extern \"C\" */")
    lines.append("")
    lines.append("static JNINativeMethod gNXMethods[] = {")
    for fn in functions:
        cls = fn.class_name[1:-1].replace("/", ".") if fn.class_name.startswith("L") else fn.class_name
        symbol = _native_symbol(fn.class_name, fn.name, fn.proto)
        lines.append(
            f'    {{ "{fn.name}", "{fn.proto}", (void*)&{symbol} }},  /* {cls} */'
        )
    lines.append("};")
    lines.append("")
    lines.append("int NXShield_RegisterNatives(JNIEnv* env, jclass clazz) {")
    lines.append(f"    int count = {len(functions)};")
    lines.append("    /* Register per declaring class in the host loader. */")
    lines.append("    return JNI_OK;")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def generate_report(functions: List[VmFunction]) -> str:
    from collections import Counter

    by_class = Counter(fn.class_name for fn in functions)
    lines = ["# NXShield 抽函数报告", "", f"- 抽取方法总数: {len(functions)}", ""]
    lines.append("## 按类分布")
    lines.append("")
    for cls, n in by_class.most_common():
        lines.append(f"- `{cls}`: {n}")
    lines.append("")
    lines.append("## 方法清单（前 200）")
    lines.append("")
    lines.append("| VM 索引 | 类 | 方法 | 原型 | 寄存器 | 字节码大小 |")
    lines.append("| --- | --- | --- | --- | --- | --- |")
    for fn in functions[:200]:
        lines.append(
            f"| {fn.method_idx} | {fn.class_name} | {fn.name} | {fn.proto} | {fn.registers} | {len(fn.bytecode)} |"
        )
    lines.append("")
    return "\n".join(lines)
